name: ghostwriter_production_nginx

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * 0"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ghostwriter Repository
        uses: actions/checkout@v4
        with:
          repository: GhostManager/Ghostwriter
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (MAIN)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/production/nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ghostwriter_production_nginx:latest
