name: WhosAtMyFeeder

on:
  workflow_dispatch:
  schedule:
    - cron: "35 7 * * 0"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WhosAtMyFeeder Repository
        uses: actions/checkout@v4
        with:
          repository: mmcc-xx/whosatmyfeeder
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Download model
        run: |
          curl -O https://raw.githubusercontent.com/zarguell/auto_container_builds/main/assets/model.tflite
      -
        name: Build and push (MAIN)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whosatmyfeeder:latest
